image:
  repository: emjotwpr/darkstat-exporter
  pullPolicy: Always
  tag: "latest"

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: false
  #  className: "nginx"
  #  annotations:
  #    nginx.ingress.kubernetes.io/rewrite-target: /$2
  #    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  #  hosts:
  #    - host: k8s.lan
  #      paths:
  #        - path: /darkstat-exporter(/|$)(.*)
  #          pathType: ImplementationSpecific
  #  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 100m
    memory: 32M

livenessProbe:
  httpGet:
    path: /metrics
    port: 9090
readinessProbe:
  httpGet:
    path: /metrics
    port: 9090

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
- name: config-volume
  configMap:
    name: darkstat-exporter-config

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
- name: config-volume
  mountPath: "/config.yaml"

nodeSelector: {}

tolerations: []

affinity: {}

envFrom: {}
